# Generated by Django 4.2.26 on 2025-11-19 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('rating', models.FloatField(default=4.5)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('created_by_name', models.CharField(blank=True, max_length=100)),
                ('created_by_avatar_url', models.URLField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('STATION_LOCKER', 'Station Locker'), ('CAFE_STORAGE', 'Cafe Storage'), ('PRIVATE_STORAGE', 'Private Storage')], max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(default=4.5)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('price_small_per_day', models.PositiveIntegerField()),
                ('price_medium_per_day', models.PositiveIntegerField()),
                ('price_large_per_day', models.PositiveIntegerField()),
                ('open_time_text', models.CharField(blank=True, max_length=100)),
                ('distance_from_center_m', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LuggageBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('dropoff_time', models.TimeField(blank=True, null=True)),
                ('small_count', models.PositiveIntegerField(default=0)),
                ('medium_count', models.PositiveIntegerField(default=0)),
                ('large_count', models.PositiveIntegerField(default=0)),
                ('total_price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.storagelocation')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.travelerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CourseStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('image_url', models.URLField(blank=True)),
                ('walk_minutes_from_prev', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_from_prev_m', models.PositiveIntegerField(blank=True, null=True)),
                ('stay_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='api.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.storagelocation'),
        ),
    ]
