# Generated by Django 4.2.26 on 2025-11-19 08:58

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagelocation',
            name='price_large_per_day',
        ),
        migrations.RemoveField(
            model_name='storagelocation',
            name='price_medium_per_day',
        ),
        migrations.RemoveField(
            model_name='storagelocation',
            name='price_small_per_day',
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='price_large_per_hour',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='price_medium_per_hour',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='price_small_per_hour',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
