# Generated by Django 4.2.26 on 2025-11-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_storagelocation_price_large_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelocation',
            name='district',
            field=models.CharField(choices=[('YONGSAN', 'Yongsan-gu'), ('JONGNO', 'Jongno-gu'), ('MAPO', 'Mapo-gu')], default='JONGNO', max_length=20),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='type',
            field=models.CharField(choices=[('STATION_LOCKER', 'Station Locker'), ('CAFE_STORAGE', 'Local Storage'), ('PRIVATE_STORAGE', 'Private Storage')], max_length=20),
        ),
    ]
