# Generated by Django 4.2.26 on 2025-12-03 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_storagelocation_district_alter_storagelocation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRecommender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar_url', models.URLField(blank=True)),
                ('country_flag_emoji', models.CharField(blank=True, max_length=8)),
                ('visited_text', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('routes_count', models.PositiveIntegerField(default=0)),
                ('cities_count', models.PositiveIntegerField(default=0)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('is_representative', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommenders', to='api.course')),
            ],
        ),
    ]
